/**
 * editor/save.ts — Turns the edited layout back into layout.ts and posts it to
 * the dev server.
 * Owns: the raw-source snapshot, the save call, and the dirty accounting.
 *
 * The raw source arrives through Vite's `?raw` import, so the browser holds
 * both the parsed layout and the exact text it was parsed from. All the
 * decisions about what to rewrite happen here, under `npm run typecheck`; the
 * server side is a byte writer that checks the path and little else.
 */
import layoutSource from "../world/hollowmere/layout.ts?raw";
import type { Heightfield, MapLayout } from "../world/layout";
import { MAX_WALKABLE_GRADE } from "../world/TerrainField";
import {
  bindBaselines,
  serializeLayout,
  validateScan,
  type Baselines,
  type SerializeError,
} from "./serialize";
import { scanLayout, type Scan } from "./sourceScan";

/** The paths the dev-server plugin will accept. Must match vite.config.ts. */
const LAYOUT_PATH = "src/world/hollowmere/layout.ts";
const HEIGHTS_PATH = "src/world/hollowmere/heights.ts";

export interface SaveResult {
  ok: boolean;
  message: string;
}

/**
 * The heightfield as its own module.
 *
 * Regenerated wholesale rather than patched line by line, which is the exact
 * opposite of how layout.ts is treated — and right for the same reason. That
 * file is authored: it carries an ASCII map, district commentary and named
 * constants that a generator would destroy. This one is several thousand bare
 * numbers that nobody will ever hand-edit, so there is nothing to preserve.
 *
 * One row per line so a diff shows which strips of the map moved rather than
 * one unreadable mega-line.
 */
export function serializeHeights(field: Heightfield): string {
  const row = field.size + 1;
  const rows: string[] = [];
  for (let j = 0; j < row; j++) {
    const line = field.heights
      .slice(j * row, (j + 1) * row)
      .map((v) => String(Math.round(v * 100) / 100))
      .join(",");
    rows.push(`    ${line},`);
  }
  const span = field.size * field.cell;
  return `/**
 * hollowmere/heights.ts — GENERATED by the map editor's terrain mode (F2, then
 * T). Do not hand-edit: the editor rewrites this file wholesale on Ctrl+S.
 *
 * This is the shape of the valley floor — one height per grid vertex, row-major
 * from the -X/-Z corner. It lives apart from layout.ts on purpose: that file is
 * authored, carries an ASCII map of the village and per-district commentary,
 * and is patched line by line by the editor. Several thousand bare numbers have
 * no business in it.
 *
 * ${field.size}x${field.size} cells of ${field.cell} m over the ${span} m map, so ${row}x${row} vertices.
 * Keep any single-cell step under ${(field.cell * MAX_WALKABLE_GRADE).toFixed(2)} m or the nav graph stops
 * linking across it and whatever is beyond becomes an island.
 */
import type { Heightfield } from "../layout";

export const HollowmereHeights: Heightfield = {
  size: ${field.size},
  cell: ${field.cell},
  // Row-major, +Z per row.
  heights: [
${rows.join("\n")}
  ],
};
`;
}

export class LayoutSaver {
  private scan: Scan;
  /**
   * Each live layout entry, tied to the source line it came from and to the
   * values it had then. Every "has this changed?" question is answered against
   * this, which is what lets untouched entries be copied from source rather
   * than regenerated — and, because it is keyed by object identity, what lets
   * entries be added and deleted without the rest of the file shifting.
   */
  private baselines: Baselines = new WeakMap();
  private scanError: string | null = null;

  constructor(current: MapLayout) {
    this.scan = scanLayout(layoutSource);
    try {
      validateScan(this.scan);
      this.baselines = bindBaselines(this.scan, current);
    } catch (err) {
      this.scanError = String((err as SerializeError).message ?? err);
    }
  }

  /** Non-null when the source could not be modelled and saving is unsafe. */
  get blocked(): string | null {
    return this.scanError;
  }

  /** The file contents a save would write, without writing them. */
  preview(current: MapLayout): string {
    return serializeLayout(this.scan, this.baselines, current).source;
  }

  async save(current: MapLayout): Promise<SaveResult> {
    if (this.scanError) return { ok: false, message: this.scanError };

    let source: string;
    let skipped: string[];
    try {
      ({ source, skipped } = serializeLayout(this.scan, this.baselines, current));
    } catch (err) {
      return { ok: false, message: String((err as Error).message ?? err) };
    }

    try {
      const res = await fetch("/__layout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ path: LAYOUT_PATH, source }),
      });
      const data = (await res.json()) as { ok?: boolean; error?: string };
      if (!res.ok || !data.ok) {
        return { ok: false, message: data.error ?? `HTTP ${res.status}` };
      }
      // The file on disk is now what we just sent, so subsequent saves must
      // diff against it — otherwise the second save would re-apply the first
      // one's edits on top of stale text. Re-binding here is also what gives
      // entries added in this session a source line of their own, so editing
      // one again rewrites its line instead of appending a second copy.
      this.scan = scanLayout(source);
      this.baselines = bindBaselines(this.scan, current);
    } catch (err) {
      return { ok: false, message: `dev server unreachable: ${String(err)}` };
    }

    // The floor is a second file, written only when the map has one. Sent
    // after the layout so a failure here cannot leave layout.ts unwritten
    // while the heights it refers to have already moved.
    if (current.terrain) {
      const wrote = await post(HEIGHTS_PATH, serializeHeights(current.terrain));
      if (!wrote.ok) return wrote;
    }

    return {
      ok: true,
      message: skipped.length
        ? `saved — ${skipped.length} unparseable ${
            skipped.length > 1 ? "entries" : "entry"
          } left as-is`
        : current.terrain
          ? "saved layout.ts + heights.ts"
          : "saved to layout.ts",
    };
  }
}

/** POSTs one file to the dev server's write endpoint. */
async function post(path: string, source: string): Promise<SaveResult> {
  try {
    const res = await fetch("/__layout", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ path, source }),
    });
    const data = (await res.json()) as { ok?: boolean; error?: string };
    if (!res.ok || !data.ok) {
      return { ok: false, message: data.error ?? `HTTP ${res.status}` };
    }
    return { ok: true, message: "saved" };
  } catch (err) {
    return { ok: false, message: `dev server unreachable: ${String(err)}` };
  }
}
